### ISSUE TITLE
Iniciamos con etiquetas HTML básicas

### ISSUE THREAD

**Issue by saulcontreras** [vpj-mati/full-stack-cami-barby#31]
- [x] Crear una rama en base MAIN con un nombre que identifique que vamos a trabajar con nuevos elementos HTML
- [x] Agregar una carpeta con la fecha del día de hoy con el formato acostumbra --> YYYYMMDD por ejemplo 20240426
- [x] Agregar un archivo nuevo con extensión .html y de nombre de cada uno + elementos basicos según corresponda todo en minúscula ej: matis-elementos-basicos.html
- [x] Agregar la estructura básica de HTML al archivo creado y agregar etiquetas iniciales para comenzar a ver como se representan en un navegador web. Uno de esos elemento será la etiqueta "a" que nos permitirá navegar a otra página de nuestro compañero, ejemplo: Matias crea link para navegar a Cami, Cami crea link para navegar a Barby y Barby crea link para navegar a Mati. 
- [x] Una vez que estemos conformes con los cambios, comiteamos localmente los mismos en la nueva rama, y pusheamos a nuestro repositorio en la nube
- [x] Solicitamos el Pull Request (PR) o Merge Request (MR) a la rama MAIN del proyecto FORKEADO
- [x]  Una vez finalizada la fusión (MERGE) volver a sincronizar nuestra rama MAIN con la opción SYNC en nuestro perfil.

**Comment by saulcontreras** [comment]
bary mi archivo se llama matis-elementos-basicos.html para que puedas crear el link

**Comment by camilazarte** [comment]
Mati mi archivo se llama cami-elementos-basicos.html para que puedas crear el link.

**Comment by barby-lazarte** [comment]
Cami ,mi archivo se llama Barby-elementos-basicos.html, para que puedas crear el link.

**Comment by camilazarte** [comment]
barby, mi archivo se llama cami-elementos-basicos.html

**Comment by barby-lazarte** [comment]
Cami, mi archivo se llama BarbyElementosBasicos.html
