### ISSUE TITLE
Iniciamos con elementos de HTML - Elementos de Formato

### ISSUE THREAD

**Issue by saulcontreras** [vpj-mati/full-stack-cami-barby#37]
- [x] Crear una rama en base MAIN con un nombre que identifique que vamos a trabajar con nuevos elementos HTML de FORMATO
- [x] Agregar una carpeta con la fecha del día de hoy con el formato acostumbra --> YYYYMMDD por ejemplo 20240426
- [x] Agregar un archivo nuevo con extensión .html y de nombre de cada uno + elementos basicos según corresponda todo en minúscula ej: matis-elementos-basicos-formato.html
- [x] Agregar la estructura básica de HTML al archivo creado y agregar etiquetas iniciales de FORMATO para comenzar a ver como se representan en un navegador web. Trabaje con los siguientes elementos dentro del contenido de un elemento p con un texto LOREM de 100 de longitud y verifique su representación visual, :
b
strong
i
em
mark
small
del
ins
sub
sup

Uno de esos elemento será la etiqueta "a" que nos permitirá navegar a otra página de nuestro compañero, ejemplo: Matias crea link para navegar a Cami, Cami crea link para navegar a Barby y Barby crea link para navegar a Mati. 
- [x] Una vez que estemos conformes con los cambios, comiteamos localmente los mismos en la nueva rama, y pusheamos a nuestro repositorio en la nube
- [x] Solicitamos el Pull Request (PR) o Merge Request (MR) a la rama MAIN del proyecto FORKEADO
- [x]  Una vez finalizada la fusión (MERGE) volver a sincronizar nuestra rama MAIN con la opción SYNC en nuestro perfil.

**Comment by camilazarte** [comment]
cami-elementos-basicos-formato.html

**Comment by barby-lazarte** [comment]
cami, el nombre de mi archivo es, Barby-elementos-basicos-formato.html
