### ISSUE TITLE
Iniciamos con Otros Elementos HTML - Formularios

### ISSUE THREAD

**Issue by saulcontreras** [vpj-mati/full-stack-cami-barby#41]
- [x] Crear una rama en base MAIN con un nombre que identifique que vamos a trabajar con nuevos elementos HTML de FORMULARIOS
- [x] Agregar una carpeta con la fecha del día de hoy con el formato acostumbra --> YYYYMMDD por ejemplo 20240426
- [x] Agregar un archivo nuevo con extensión .html y de nombre de cada uno + elementos formulario según corresponda todo en minúscula ej: matis-elementos-formulario-formato.html
- [x] Agregar la estructura básica de HTML al archivo creado y agregar etiquetas iniciales de FOMRULARIO para comenzar a ver como se representan en un navegador web. Trabaje con los siguientes elementos dentro del contenido de un elemento FORM y verifique su representación visual, :
input type text
input type password
input type radio
input type submit
input type button
input type file
textarea
select

agregar un elemento label a cada elemento para orientar al usuario

Uno de esos elemento será la etiqueta "a" que nos permitirá navegar a otra página de nuestro compañero, ejemplo: Matias crea link para navegar a Cami, Cami crea link para navegar a Barby y Barby crea link para navegar a Mati. 
- [x] Una vez que estemos conformes con los cambios, comiteamos localmente los mismos en la nueva rama, y pusheamos a nuestro repositorio en la nube
- [x] Solicitamos el Pull Request (PR) o Merge Request (MR) a la rama MAIN del proyecto FORKEADO
- [x]  Una vez finalizada la fusión (MERGE) volver a sincronizar nuestra rama MAIN con la opción SYNC en nuestro perfil.

**Comment by barby-lazarte** [comment]
Cami,mi archivo se llama Barby-elementos-formularios.html

**Comment by camilazarte** [comment]
Barby mi archivo se llama cami-elementos-formulario.html para q lo coloques en tu pagina.
